<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
    <link rel="stylesheet" href="/css/styles.css">
</head>
<body>
<textarea id="code_snippet" class="snippet">// write your code here</textarea>
<br>
<label for="time_restriction">Time restriction:<input id="time_restriction" type="text" value="0"></label>
<br>
<label for="views_restriction">Views restriction:</label><input id="views_restriction" type="text" value="0">
<br>
<button id="send_snippet" type="submit" onclick="send();">Submit</button>
<script src="/js/codeShare.js"></script>
</body>
</html>